### ISSUE TITLE
A demo will help

### ISSUE THREAD

**Issue by jsxyhelu** [ilhamadun/WiringPiKeypad#1]
this project is great.But I think A demo to show " how to use" will help,wait for you reply.
thanks

**Comment by ilhamadun** [comment]
Apologize for the lack of documentation.

First, you need to understand that this project support this kind of matrix keyboard:

![Matrix Keypad](https://circuitdigest.com/sites/default/files/inlineimages/4x4-matrix-keypad.gif)

You can see the example in [this project](https://github.com/ArjunaElins/Arjuna/blob/master/Software/MPU/src/Setup.cpp#L152). Basically, you initialize the `WiringPiKeypad` by defining the keypad layout and the pin number of the rows and columns.

```c++
int row[4] = {21, 22, 23, 24};
int column[4] = {1, 2, 3, 4};
std::vector<std::vector<char>> matrix {
    {'D', 'C', 'B', 'A'},
    {'#', '9', '6', '3'},
    {'0', '8', '5', '2'},
    {'*', '7', '4', '1'}
};

WiringPiKeypad *keypad = new WiringPiKeypad(4, 4);

keypad->setRowPin(row);
keypad->setColumnPin(column);
keypad->setMatrix(matrix);

char key = keypad->getKey();
```

The `getKey()` method will block until the key is pressed, and it returns a char such as `'1'`.

I realize that it doesn't follow some of the best practices, since I wrote this 4 years ago (heck, I don't even remember why I need to put the `matrix` upside down, I think it's about the wiring). Anyway, the example above should work.

**Comment by ilhamadun** [comment]
Also, if you confirmed that the example works, I will add it to the README (or you could make a pull request).

**Comment by jsxyhelu** [comment]
great ! I will make a pull request now
